config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  devise_for :users
  
  
  root 'home#index'

  namespace :admin do
    resources :instructors
    resources :courses do
      resources :lessons
    end

    
  end
  resources :instructors, only: %i[show index]
  resources :courses, only: %i[show index]  do
    resources :lessons, only:  %i[show index] 
    post 'order', on: :member
    get 'my_courses', on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :courses, only: %i[index show create update destroy], param: :code
    end
  end

end

app/models/instructor.rb
class Instructor < ApplicationRecord
  validates :name, :email, presence: true
  validates :email, uniqueness: true
  has_one_attached :profile_picture
  has_many :courses
end

app/controllers/admin/instructors_controller.rb
class Admin::InstructorsController < Admin::AdminController
  def index
    @instructors = Instructor.all
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

  def new
    @instructor = Instructor.new
  end

  def create
    @instructor = Instructor.new(instructor_params)
   if @instructor.save
    flash[:success] = t('.success')
    redirect_to [:admin, @instructor]
  else  
    flash[:fail] = t('.fail')
    render :new
  end
end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def update
    @instructor = Instructor.find(params[:id])
  if @instructor.update(instructor_params)
    flash[:success] = t('.success')
    redirect_to [:admin, @instructor]
  else 
  flash[:fail] = t('.fail')
  render :edit
    end
  end

def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy
    flash[:success] = t('.success')
    redirect_to root_path
  end

  private
  def instructor_params
    params.require(:instructor).permit(:name, :email, :bio, :profile_picture)
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
    @instructors = Instructor.all
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

end

app/views/admin/instructors/_form.html.erb
<div class="card mx-auto" style="width: 50rem;">
  <div class="card-body">
<%= form_with model: [:admin, instructor] do |f| %>
<div class="row g-2 ml-2">
  <div class="col-md-6">
<%= f.label :name, "Nome", class:"form-label" %>
<%= f.text_field :name, class:"form-control" %>
  </div>

  <div class="col-md-6">
<%= f.label :email, "Email", class:"form-label" %>
<%= f.text_area :email, class:"form-control" %>
</div>

  <div class="col-md-6">
<%= f.label :bio, "Descrição", class:"form-label" %>
<%= f.text_field :bio, class:"form-control" %>
</div>


  <div class="col-md-6">
<%= f.label :profile_picture, "Foto de perfil", class:"form-label" %>
<%= f.file_field :profile_picture, class:"form-select"  %> <br>
</div>
</div>

<%= f.submit button_text, class:"btn btn-outline-dark btn-sm"%>
<%= link_to t('links.back'), root_path, class:"btn btn-outline-dark btn-sm" %>
  
<% end %>
  </div>
</div>

app/views/admin/instructors/edit.html.erb
<h1 class="text-center"><%= t('.title') %> </h1>

<%= render partial: 'form', locals: {instructor:@instructor, button_text: 'Atualizar Professor'} %>

app/views/admin/instructors/index.html.erb
<% if @instructors.empty?%>
<p>Nenhum professor disponível</p>
<% else %>

  <div class="card">
        <div class="row">
        <% @instructors.each do |instructor| %>
         <div class="card col-3 text-center">
            <% if instructor.profile_picture.attached? %>
              <%= image_tag instructor.profile_picture, size: "100x100", class:"mx-auto rounded-circle"%> 
            <% end %>
          <h5> <%= link_to instructor.name, admin_instructor_path(instructor) %> </h5>
          </div>
          <% end %>
        </div>
</div>
<% end %>
<%= link_to 'Registrar um Professor', new_admin_instructor_path, class:"btn btn-success btn-sm" %>
<%= link_to 'Voltar', root_path, class:"btn btn-outline-dark btn-sm"%>



  

app/views/admin/instructors/new.html.erb
<h1 class="text-center"><%= t('.title') %> </h1>
<%= render partial: 'form', locals: {instructor:@instructor, button_text: 'Cadastrar Professor'} %>

app/views/admin/instructors/show.html.erb
<div class="card mx-auto" style="width: 25rem;">
  <% if @instructor.profile_picture.attached? %>
  <%= image_tag @instructor.profile_picture, size: "300x250", class:"mx-auto" %> 
  <% end %>
  <div class="card-body mx-auto">
    <h5 class="card-title">Nome: <%= @instructor.name %></h5>
    <p class="card-text">Email: <%= @instructor.email %> </p>
    <p class="card-text">Descrição:  <%= @instructor.bio %></p>
        <%= link_to t('links.edit_instructor'), edit_admin_instructor_path(@instructor), class:"btn btn-warning"%>
        <%= link_to t('links.destroy_instructor'),admin_instructor_path, method: :delete , data: {confirm: 'Deseja excluir esse cadastro?'}, class:"btn btn-danger" %>
        <%= link_to t('links.back'), admin_instructors_path, class:"btn btn-outline-dark"%>
  </div>
</div>