config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  devise_for :users
  
  
  root 'home#index'

  namespace :admin do
    resources :instructors
    resources :courses do
      resources :lessons
    end

    
  end
  resources :instructors, only: %i[show index]
  resources :courses, only: %i[show index]  do
    resources :lessons, only:  %i[show index] 
    post 'order', on: :member
    get 'my_courses', on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :courses, only: %i[index show create update destroy], param: :code
    end
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeplay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Code Play', root_path, class:"navbar-brand" %>
      <div class="collapse navbar-collapse">
       <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
         <% if  user_signed_in?%>

        <li class="nav-item">
           <span class="text-light nav-link disabled"><%= current_user.email %></span>
        </li>

        <li class="nav-item active">
         <%= link_to 'Cursos', admin_courses_path, class:"nav-link"  %> 
        </li>
         <li class="nav-item">
          <%= link_to 'Professores', admin_instructors_path, class:"nav-link"  %>
        </li>
         <%= link_to 'Sair',  destroy_user_session_path, method: :delete, class:"nav-link" %>
         <% else %>
          <li class="nav-item active">
          <%= link_to 'Registrar-me', new_user_registration_path, class:"nav-link"  %> 
        </li>
          <li class="nav-item active">
          <%= link_to 'Logar', new_user_session_path, class:"nav-link" %>
        </li>

       <% end %>

      </li>
    </ul>
  </div>
</nav>
  </header>
      <% flash.each do |nome, mensagem| %>
      <%= content_tag :div, mensagem, class: 'base-alert ' + nome %>
    <% end %>
      <div class="container-fluid">
        <%= yield %>
      </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeplay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Code Play', root_path, class:"navbar-brand" %>
      <div class="collapse navbar-collapse">
       <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
         <% if  student_signed_in?%>

        <li class="nav-item">
           <span class="text-light nav-link disabled"><%= current_student.email %></span>
        </li>

        <li class="nav-item active">
         <%= link_to 'Cursos', courses_path, class:"nav-link"  %> 
        </li>

         <li class="nav-item">
          <%= link_to 'Professores', instructors_path, class:"nav-link"  %>
        </li>
         <%= link_to 'Sair',  destroy_student_session_path, method: :delete, class:"nav-link" %>
         <% else %>
          <li class="nav-item active">
          <%= link_to 'Registrar-me', new_student_registration_path, class:"nav-link"  %> 
        </li>
          <li class="nav-item active">
          <%= link_to 'Logar', new_student_session_path, class:"nav-link" %>
        </li>

       <% end %>

      </li>
    </ul>
  </div>
</nav>
  </header>
      <% flash.each do |nome, mensagem| %>
      <%= content_tag :div, mensagem, class: 'base-alert ' + nome %>
    <% end %>
      <div class="container-fluid">
        <%= yield %>
      </div>
  </body>
</html>